### ISSUE TITLE
openTab patch is breaking Hotkey Helper features

### ISSUE THREAD

**Issue by pjeby** [alberti42/obsidian-plugins-annotations#14]
After I installed this plugin to confirm and fix #5 in HH, I noticed that some HH features stopped working properly as well.  The issue is here:

```ts
        // Patch openTab to detect when a tab is opened
        const removeMonkeyPatchForSetting = around(this.app.setting, {
            openTab: (next: (tab: SettingTab) => void) => {
                return async function(this: Setting, tab: SettingTab) {
                    if (tab && tab.id === 'community-plugins') {
                        if(self.observedTab!==tab) {
                            await self.observeCommunityPluginsTab(tab);
                            self.patchCommunityPluginSettingTab(tab);
                        }
                    }
                    next.call(this, tab);
                };
            },
```

This is turning a synchronous method in Obsidian (openTab) into an async one, which is breaking its contract and will not work properly with *any* plugin relying on openTab or openTabById to have their normal synchronous behavior, even if they aren't doing any monkeypatching that involves it.  (HH doesn't patch it, just calls it by way of openTabById, expecting the tab to be displayed when the function returns.)

I've only looked at this code superficially, but my guess would be that there is no reason to have the `async` or `await` here, as none of the code in question appears to rely on observeCommunityPluginsTab() actually being finished in order to work.  (And even if you did need patchCommunityPluginSettingsTab to run after observeCommunityPluginsTab() finishes all its async loading actions, you could just use .then() and not make the patched function async.

**Comment by pjeby** [comment]
On further examination, it looks like patchCommunityPluginSettingsTab is always called after observeCommunityPluginsTab, so it could just be called directly *from* there instead, which would avoid the need for either `await` or `then` in the openTab patch.  (Given the plugin's onload code, it's apparent that you don't need to make any of it run before the tab is opened, either, so the patch definitely doesn't need to be async.  For that matter, if the patching and observing is only supposed to be done once, you could use

```ts
const activeTab = this.app.setting.settingTabs.find(t => t.id === "community-plugins");`
```
in your onload and do away with the need to patch openTab at all.)

**Comment by alberti42** [comment]
Hi PJ, thanks a lot for detailed feedback and the insightful suggestions.

When I made `openTab` async, I did not think that this would break the behavior of other parts of the code. You are totally right. So, I reverted to a standard synchronous function.

The problem was not much with calling `patchCommunityPluginSettingTab` which could have been shifted inside of `observeCommunityPluginsTab` as you suggested, but rather waiting that all this code has finished executing before calling the original `openTab` function through `next.call(this, tab);`.

I think there was a simple solution. I made use of `then` to ensure that `next.call(this, tab);` is called only after the rendering functions have been patched. It now works and I released a new version of the plugin https://github.com/alberti42/obsidian-plugins-annotations/releases/tag/1.7.5.

I also checked that the new version of your plugin now works seamlessly with my plugin. Great. Thanks to [ksdavidc](https://github.com/ksdavidc) we have fixed a bug in each respective plugin.

**Comment by pjeby** [comment]
Thanks for the quick update, but the problem is that `next.call()` needs to be called *immediately*, otherwise any code that opens the community plugins tab and then acts on it will have a problem.  It would be much better if you just called next.call() at the top of your patch, always.  If you need to patch rendering methods ahead of time, you can do that when the plugin starts, just search for the tab at workspace load using the `.find()` call I showed above -- in which case you could avoid the openTab patch altogether.

**Comment by ksdavidc** [comment]
Get a room, guys. ;-)

For me this has been a fascinating (perhaps painful for you) excursion into the innards of the purple beast. 

A lot of apps end up developing somewhat ambiguous relationships with their "plugineers". They provide critical functions as far as users are concerned, but are hacking away at your darlings. It becomes inherently difficult to manage all the moving parts, personalities, and priorities. 

One of the things I especially like about Obsidian is its modularity. The mix and match quality of it makes it much better than having to wake up a herd of elephants just to cross the road. I have my complaints, but for the most part I am amazed at how flexible it can be, despite being a victim of its own success. I mean look at me, 236 plugins just to get one vault to live up to its potential...and somehow, thanks to heroes like you, it works (at least until the next crossroads). I like that it can still be good at doing things it was not designed to do. 

Lastly, let me say I think both of your plugins are invaluable for haphazard newbies like me who are trying to manage the complexity. Arguably, a lot more of the internal maintenance tools like these should be incorporated into the mother ship, but I can see there is also an imperative to keep the core lean.

**Comment by alberti42** [comment]
Hi PJ, thanks for the piece of advice and explanation about the `then` mechanism. I agree that using `then` does not ensure a synchronous execution of `openTab`.

 I use:
 ```typescript
this.app.setting.settingTabs.find(t => t.id === "community-plugins");`
```
and streamlined the rest of the code. I completely removed the Observer on the community plugin tab. It was a remnant from several code refactorings ago.

I created a new release of the app where there is no patch to `openTab` at all. The fewer, the better.

However, I still have a question that bugs me since the beginning and is related to this problem. I am really troubled by the fact that when I have multiple Obsidian devices, if I change the settings on one device, the settings are synchronized to the second device, but there is no mechanism (which I know) to detect that settings are changed.

In the present state, my plugin loads the settings on loading the application or when the plugin is installed. If the user keeps Obsidian open on two computers, works on computer B and changes some settings, and then comes back to computer A, there is no way my plugin learns the settings have changed! So, when he/she opens the setting pane on computer A, there would be bewilderment and disappointment that the settings are not there anymore. Of course, it would be sufficient to close and reopen Obsidian, but the user does not know this. So she/he would be frustrated and start retyping the changes manually... this is horrendous.

A way around is to use `chokidar` library to detect changes to `data.json`. However, I am afraid this is not going to work on mobile devices. If it works for mobile devices, then this could be a good solution.

However, I am really wondering whether there is an official way to detect changes in the settings happening because of synchronization between multiple devices. This is a huge problem not just affecting my plugin but possibly any other plugins.

**Comment by alberti42** [comment]
I found this function [onExternalSettingsChange](https://docs.obsidian.md/Reference/TypeScript+API/Plugin/onExternalSettingsChange). I will immediately give it a try.

**Comment by alberti42** [comment]
I have released a new [version](https://github.com/alberti42/obsidian-plugins-annotations/releases/tag/1.7.7) with the following new features:

> Detect changes to `data.json` made by the synchronisation engine (Obsidian or Google Drive or Dropbox etc) or any external editor. If the Community Preferences window is active, the changes will be shown immediately. Similarly, if changes are made using an external editor to the MarkDown file that stores the personal annotations, these changes will be detected and the preferences pane will be updated immediately to reflect the new changes.

I made many other small changes to clean up the code. Let's hope no new bugs have crept in.

**Comment by pjeby** [comment]
Thanks!
